### PR TITLE
feat: add calculation parameters as state attributes

### LINKED ISSUE #9: Feature: Add temp and humidity as state_attributes
Would be nice to have the values as state attributes on MoldRiskBaseSensor for temperature and humidity for easy access.

### PR DESCRIPTION
**Pull request by bj00rn**
add temperature and humidity as state attributes where relevant

fixes #9

### CODE REVIEW

**Comment by Strixx76** [comment]
Every time a attribute changes a new record is created in the database. There for it is not a good idea to have a attribute that changes more often than the state. This change will cause the recorder to store probably thousands, if not tens of thousands more records for this integration.
If it should be merged it needs to be [excluded from recorder history](https://developers.home-assistant.io/docs/core/entity?_highlight=state&_highlight=attributes#excluding-state-attributes-from-recorder-history). This way of excluding is new, so you probably also need to update the Home Assistant version to the correct one.

**Comment by bj00rn** [comment]
> Every time a attribute changes a new record is created in the database. There for it is not a good idea to have a attribute that changes more often than the state. This change will cause the recorder to store probably thousands, if not tens of thousands more records for this integration. If it should be merged it needs to be [excluded from recorder history](https://developers.home-assistant.io/docs/core/entity?_highlight=state&_highlight=attributes#excluding-state-attributes-from-recorder-history). This way of excluding is new, so you probably also need to update the Home Assistant version to the correct one.

I think that this reasoning mostly applies to polling sensors. I could be mistaken though.

These are non polling sensors(`_attr_should_poll = False`) and my understanding is that state and attributes are not recorded by the HA state machine until [async_write_ha_state()](https://developers.home-assistant.io/docs/integration_fetching_data/#push-vs-poll) is called. The integration only calls `async_write_ha_state()`if state was actually changed, hence nothing is recorded otherwise.


```
@callback
    def _async_state_listener(self, event: Event) -> None:
        """ Listen for sensor state changes. """
        self._mold_calc.async_event_receiver(event)
        if self._mold_calc.risk != self._risk: # check if new state
            self._risk = self._mold_calc.risk
            self._temperature = self._mold_calc.temperature
            self._humidity = self._mold_calc.humidity
            self.async_write_ha_state()
```

**Comment by Strixx76** [comment]
Yes, you are of course correct. It is not stored until you call `async_write_ha_state()`. But unless you call that the attribute will not update, and what is then the point of having the attribute?
I have taken I quick look at your suggested code change and all you will see in the attributes is what the temperature and humidity was when the sensor changed state last time, and not current temperature and humidity. Will that not confuse the user?

When I first wrote this integration I was about to add the temperature and humidity as attributes, but I decided not to do so because it would go against the recommendations on the developer site. I thought that maybe you could reduce database growth, due to this feature, was to implement the above mentioned attribute.
But when I think about it it will only partially help. Because even if we omits these attributes the two states will still be recorded more often. In my own case I have a ESPHome sensor reporting temperature and humidity every 30 seconds. But the state of the Risk Index sensor almost never changes, and the Limit sensor changes in average only a couple of times per day. So instead of 10 to 20 records in the database, I would get 2880 records.
I think I need to think and check the source for the recorder a bit more, before implementing this, or if you could find out how this actually will impact the database.

**Comment by bj00rn** [comment]
> all you will see in the attributes is what the temperature and humidity was when the sensor changed state last time, and not current temperature and humidity. Will that not confuse the user?

I took inspiration here from the excellent [thermal comfort integration](https://github.com/dolezsa/thermal_comfort). All calculated sensors include the parameters that gave rise to the most recent value. See dew point example below.

image

> So instead of 10 to 20 records in the database, I would get 2880 records.
I think I need to think and check the source for the recorder a bit more, before implementing this, or if you could find out how this actually will impact the database.

That's strange.. the way I read the code no state should ever be recorded unless the actual value is changed. Maybe throw some debug log lines in there?

Side note, consider merging this integration into thermal comfort, there is a FR in there on a mold calculation sensor 🚀

**Comment by Strixx76** [comment]
I guess I was a bit unclear. Your suggested code change will not cause more records (but bigger) in the database. But it will not show the current temperature and humidity. Instead it will only show the temperature and humidity at the time of the latest state change on the limit or risk sensor. Is that the wanted behavior?

This means that the attributes temperature and humidity will, most of the time, not show the current temperature and/or humidity. For the risk sensor the attribute can differ very much, because as long as you are at for example 0 risk, it will never change state, and therefore never update the attribute.

As an example, my on risk sensor has only once been at 1 for a very short period maybe 2 months ago. So for me those attribute on the risk sensor would then today have shown the temperature and humidity that was two months ago when the state changed back from 1 to 0. Two month ago the temperature was around 15°C (which will be what i shown in the attributes) in my crawl space and today it is around 10°C (which will not be shown toady).

**Pull request closed without merging**
